apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: loki
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: loki

  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      chart: loki
      targetRevision: 6.42.0
      helm:
        releaseName: loki
        valueFiles:
          - $repo/loki/values.yaml
    - repoURL: "https://github.com/LukaszSellmann/argocd.git"
      ref: repo

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
