apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden

  source:
    chart: vaultwarden
    repoURL: https://guerzon.github.io/vaultwarden
    targetRevision: 0.34.4
    helm:
      releaseName: vaultwarden-release
      parameters:
        - name: domain
          value: "https://vaultwarden.sellmann.pl"
        - name: ingress.enabled
          value: "true"
        - name: ingress.hostname
          value: "vaultwarden.sellmann.pl"
        - name: service.type
          value: "LoadBalancer"
        - name: storage.data.name
          value: "vaultwarden-data"
        - name: storage.data.size
          value: "15Gi"
        - name: storage.data.path
          value: "/data"
        - name: storage.data.accessMode
          value: "ReadWriteOnce"
        - name: replicas
          value: "1"
        - name: logging.logLevel
          value: "debug"

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
