apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: openwebui

  sources:
    - repoURL: https://helm.openwebui.com/
      chart: open-webui
      targetRevision: 8.14.0
      helm:
        releaseName: openwebui-release
        valueFiles:
          - $repo/openwebui/values.yaml
    - repoURL: "https://github.com/LukaszSellmann/argocd.git"
      ref: repo

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
