apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-demo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-demo-app

  sources:
    - repoURL: "https://github.com/LukaszSellmann/argocd.git"
      path: monitoring-demo-app
      targetRevision: main
      helm:
        releaseName: monitoring-demo-app
        valueFiles:
          - values.yaml

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
