apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-demo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-demo-app

  source:
    repoURL: "https://github.com/LukaszSellmann/argocd.git"
    chart:
    targetRevision: main
    path: monitoring-demo-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
