apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden

  sources:
    - repoURL: https://guerzon.github.io/vaultwarden
      chart: vaultwarden
      targetRevision: 0.34.4
      helm:
        releaseName: vaultwarden-release
        valueFiles:
          - $repo/vaultwarden/values.yaml
    - repoURL: "https://github.com/LukaszSellmann/argocd.git"
      ref: repo

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
