apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: loki

  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      chart: alloy
      targetRevision: 1.3.0
      helm:
        releaseName: alloy
        valueFiles:
          - $repo/grafana_alloy/values.yaml
    - repoURL: "https://github.com/LukaszSellmann/argocd.git"
      ref: repo

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
