apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wazuh
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: "https://kubernetes.default.svc"
    namespace: wazuh

  sources:
    - repoURL: "https://github.com/LukaszSellmann/argocd.git"
      targetRevision: main
      path: wazuh-kubernetes/envs/local-env
      kustomize:
        commonAnnotations:
          managed-by: argocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
