apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: ollama

  sources:
    - repoURL: https://helm.otwld.com/
      chart: ollama
      targetRevision: 1.34.0
      helm:
        releaseName: ollama-release
        valueFiles:
          - $repo/ollama/values.yaml
    - repoURL: "https://github.com/LukaszSellmann/argocd.git"
      ref: repo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
