apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-demo-app
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-demo-app

  source:
    repoURL: https://github.com/LukaszSellmann/demo-app.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
